docs/user_guide.md

Forseti only needs the policies and lib dirs. Also use rsync instead of cp since we want to mirror the content.

Update gsutil cp instruction for policy library

---

docs/user_guide.md

To end with /policy-library.
This was pointed out in  #18

Update sample local policy library path

---

cloudbuild.yaml
pkg/gcv/configs/config_test.go
pkg/gcv/validator_test.go

We should fix those tests, but that shouldn't block us from getting CI up & running.

Add cloudbuild config file and skip incompatible tests

---

pkg/gcv/configs/config.go
pkg/gcv/validator_test.go

Refactoring conversion to fail if the group matches, but other fields don't exist as expected.
This allows better surfacing of errors. These would have already failed in the larger execution because we have no overlap of groups between constraints/templates.

Refactoring conversion errors

---

pkg/gcv/configs/config_test.go

I was getting the following failure:
```
--- FAIL: TestCategorizeYAMLFile (0.00s)
--- FAIL: TestCategorizeYAMLFile/invalid_template_invalid_target (0.00s)
config_test.go:466: invalid template invalid target (-want, +got) :
-: <non-existent>
+: (*configs.ConstraintTemplate)(nil)
--- FAIL: TestCategorizeYAMLFile/invalid_constraint_uses_template_kind (0.00s)
config_test.go:466: invalid constraint uses template kind (-want, +got) :
-: <non-existent>
+: (*configs.Constraint)(nil)
--- FAIL: TestCategorizeYAMLFile/invalid_constraint_uses_template_api_version (0.00s)
config_test.go:466: invalid constraint uses template api version (-want, +got) :
-: <non-existent>
+: (*configs.ConstraintTemplate)(nil)
```
We don't need to look at the result at all if there's an error. Updated the test to …

Update config test

---

pkg/gcv/cf/audit.go
pkg/gcv/cf/cf_test.go

If the target is not specified, it is the equivalent of specifying "organization/*".
Fix #39.

Make default matcher behavior to match everything

---

pkg/gcv/cf/audit.go
pkg/gcv/cf/cf_test.go

See #42 for context.
Also update the test template to use the new format for targets.
We'll temporarily accept both forms (with and without gcp wrapper). The plan to is to remove the support for gcp wrapper at a later date.

Update matching logic to not require gcp wrapper field

---

pkg/gcv/cf/audit.go
pkg/gcv/cf/cf_test.go

Address https://github.com/forseti-security/policy-library/issues/104
Also add an "always violate" template in unit test, since the previous template needs a parameter.

Handle absent spec/target fields properly

---

Dockerfile
cloudbuild.yaml

This is in support of the effort in running Forseti on GKE.
I recommend we place the server Dockerfile in the root of the repository since the docker context is the entire repo.

Adding Dockerfile to build server

---

cmd/server/main.go
pkg/gcv/cf/cf.go
pkg/gcv/cf/cf_test.go
pkg/gcv/cf/parsing.go
pkg/gcv/validator.go

* This is intended to be a functional impl of Review.  Multithreaded
support will come in a following patch.
* Fix up ConstrintFramework.Reset.  Prior to this, we weren't clearing
store.  In theory, this won't really matter since we re-create inventory
on each call to audit, but this would cause weird artifacts if people
start calling AddData then Reset then Review (which we don't really plan
to support, but we would not want to support the bugs resulting from the
weird behavior).

Implement ConstraintFramework.Review

---

cmd/server/main.go
pkg/gcv/validator.go
pkg/gcv/validator_test.go

This would fix https://github.com/forseti-security/config-validator/issues/57.

allow multiple paths of policy.

---

cmd/server/main.go

This supports the case for a distroless container (sans shell) where the `policyPath` and `policyLibraryPath` can't be specified on the command line.

Policy library and path as env vars

---

pkg/gcv/configs/config.go
pkg/gcv/validator_test.go

Validator should be fail-safe that if there is a misconfiguration that results in zero configurations loaded, it should generate an error.
This should not be confused with the use case where *one* of the directory is empty but some configurations are loaded. This pull request allow that use case.

generate error when no configuration is loaded

---

pkg/gcv/configs/config.go
test/cf/templates/gcp_bq_dataset_location_v1.yaml

Resources with an OpenAPI spec were not converting properly since the
schemes were not registered.  This fixes the panic.

Fix OpenAPISpec conversion issue.

---

pkg/gcv/configs/config.go
pkg/gcv/configs/config_test.go
pkg/gcv/validator.go
test/cf/constraints/cf_gcp_storage_logging_constraint.yaml
test/cf/constraints/gcp_storage_logging_constraint.yaml

Prior matchers would format "organization/*" rather than a standard glob
formatting like "organziations/**".  This fixes legacy support for
"organziation/*" for old-style constraints.

Fix up issue with legacy matcher formatting.

---

pkg/gcv/configs/config.go
pkg/gcv/validator.go

Instead of failing on first error, this will cause FCV to emit all template and constraint errors.

Have config validator emit all constraint / constraint template errors.

---

cmd/policy-tool/lint/lint.go

Update linter to not print help text on failure and print No lint errors found. on success.

Fix linter output.

---

Makefile
build/policy-tool/Dockerfile

Add a docker image so we can incorporate this into cloudbuild for policy-tool.
Also fix up some UX issues
- was printing help on issues found, nothing on no issues
- gcs client init was causing docker image to error out

Put policy-tool in a docker image

---

cmd/policy-tool/lint/lint.go
cmd/server/main.go
pkg/gcv/parallelvalidator.go
pkg/gcv/parallelvalidator_test.go
pkg/gcv/validator.go
pkg/gcv/validator_test.go
test/cf/constraints/all_namespace_must_have_cost_center.yaml

This change is intended to simplify Validator to enable emitting results
in a format other than Violation.

Refactor threading into ParallelValidator

---

Dockerfile

This brings down local cloudbuild execution time from ~2m45s to ~50s on
consecuitive builds where go.mod/go.sum do not change.

Adjust dockerfile build step to cache mod download.

---

Makefile
cmd/policy-tool/lint/lint.go
pkg/multierror/multierror.go

We don't yet have tags for versions, so use the commit hash for the time being
to version the image that policy-library uses in CI

Have policy tool push to tag wtih commit hash.

---

build/cloudbuild/build-cloudbuild.yaml

Increase cloud build timeout from 20min to 30min because `docker build -t gcv-proto-builder -f ./build/proto/Dockerfile .` needs more than 20mins

increase cloud build timeout from 20min to 30min 

---

.gitignore
pkg/asset/asset.go

Update the error message to mention ancestors instead of resource.data. Update .gitignore to ignore build artifacts from `make pyproto`.
Resolves #147

Fix error message in UnwrapCAIResource

---

README.md

(Since we have multiple clients now, this name isn't really accurate.)

Remove Forseti name from main README

---

pkg/gcptarget/gcptarget.go
pkg/gcptarget/gcptarget_test.go

From https://cloud.google.com/resource-manager/docs/creating-managing-projects:
"The project ID must be a unique string of 6 to 30 lowercase letters, digits, or hyphens. It must start with a letter, and cannot have a trailing hyphen."

Support project IDs in gcptarget

---

pkg/gcv/configs/config.go
pkg/gcv/validator.go
pkg/gcv/validator_test.go

This splits up some of the config loading functions to allow calling them with the contents of policy constraint and policy library files, without reading from the file system. This makes it possible for another system using GCV as a library to initialize a validator by directly providing config values and not needing to read from the file system.
The semantics and usage of existing init and config loading functions are unchanged.

Refactor to allow initializing validator without a file system

---

pkg/gcptarget/gcptarget.go
pkg/gcptarget/gcptarget_test.go
pkg/gcptarget/library.go
pkg/gcv/result_test.go
pkg/targettesting/targettest.go
test/cf/constraints/cf_gcp_storage_logging_constraint.yaml
test/cf/constraints/gcp_storage_logging_constraint.yaml

ancestries / excludedAncestries matches the naming conventions for the [TF](https://github.com/GoogleCloudPlatform/config-validator/blob/f2ac3550d4bde0a292dee1c4eb3f3a4a40df8ca7/pkg/tftarget/tftarget.go#L45) / [K8s](https://github.com/open-policy-agent/gatekeeper/blob/8d09271668aa2a12da9f445ea095341146475877/pkg/target/match_schema.go#L110) targets and eliminates confusion caused by reusing the word "target".

Added support for ancestries / excludedAncestries

---

pkg/gcv/result_test.go
pkg/gcv/validator.go
pkg/gcv/validator_test.go

SanitizeAncestry fills in the ancestors / ancestry path fields if one of them is empty; ValidateAsset requires that the ancestry path is set. This means that in practice, an ancestry path must always be set. This seems unintentional, and it means that callers like terraform-validator and cft-scorecard have to work around this behavior.

Sanitize ancestry before validating an asset in ReviewAsset

---

README.md

Existing link to docs is stale since name of the default branch has changed to main.

Point user guide link to main branch of policy-library

---

Makefile
pkg/api/validator/validator.pb.go

We probably want the generation of `validator.pb.go` to be deterministic.
Fixes: #205

fix: pin aliasfix for deterministic validator.pb.go

---

Makefile
build/proto/Dockerfile
pkg/api/validator/validator.pb.go

The `golang:1.20` base image doesn't include Python 2, update the `make pyproto` process and image to support Python 3.

fix: gen pyproto with python3
