GoogleCloudPlatform/config-validator

Makefile
Also change the binary name to "config-validator" and disable cgo.
=> Update Makefile to set the Go build package

pkg/api/validator/validator.pb.go
It appears in a previous commit I forgot to run this to push a comment update.
=> running make build to update protos

docs/user_guide.md
Also address the following issues:
* #11
* #10
* #9
=> Update terraform-validator binary path 

pkg/gcv/cf/audit.go, pkg/gcv/cf/cf_test.go, pkg/gcv/validator_test.go
Also move the OSS license comment in audit.go to the top of the file and rename a few test methods in cf_test.go to remove underscores.
This fixes #34
=> Implement target and exclude mechanism

pkg/asset/asset.go, pkg/asset/proto_util.go, pkg/asset/proto_util_test.go, pkg/gcv/validator.go, pkg/gcv/validator_test.go
* Move some utility code into pkg/asset in preparation for future
changes.
=> Code refactor.

pkg/gcv/validator.go
Allows for directy reviewing after performing JSON decode, will be
easier to interface with in tools like CFT scorecard.
=> Expose API for directly reviewing an asset.

build/cloudbuild/build-cloudbuild.yaml
* Changed Images to images
* Added a container build with the short SHA of the commit as a container image tag
=> Another cloud build fix

Dockerfile
Updating golang version.  Only build linux distro.
=> Dockerfile Improvements

Dockerfile, go.mod, go.sum, pkg/gcv/configs/config.go, pkg/gcv/configs/config_test.go, pkg/gcv/configs/file.go
Resolves #84 
Tested that the policies and lib are loaded.  Haven't tested client/server interaction yet.
=> Remote library path

pkg/gcv/configs/file.go
This prevents Policy linter failure in environments that don't have GCP credentials (docker image).
=> Lazy load GCS client.

pkg/asset/asset.go, pkg/gcv/validator.go
Refactor for adding k8s template support.
=> Consolidate calls to the constraint framework client.

pkg/gcv/validator.go, pkg/gcv/validator_test.go
Also fix unit tests to check on exported surfaces.
=> Fix bug in ancestry path for JSON input.

pkg/gcv/parallelvalidator_test.go
=> Stop calling t.Fatal in goroutine

go.mod, go.sum
=> Update opa to v0.17.2

pkg/gcv/result.go, pkg/gcv/result_test.go
=> Add constraint info to violations.

cmd/policy-tool/debug/debug.go, cmd/policy-tool/policy-tool.go, pkg/api/validator/validator.pb.go
Intent is to make it easier to find inputs that encounter errors while running validator (prints raw input for cut / paste into tests).
=> Add debug command for finding errors.

pkg/asset/asset.go, pkg/gcptarget/gcptarget.go
Complements https://github.com/forseti-security/config-validator/pull/137, for #136
=> Additional changes to support org policy & access context policy

pkg/gcv/result.go, pkg/gcv/result_test.go
=> Add ancestry path to violation.

pkg/gcptarget/gcptarget_test.go
Fixes thing is just for reference, these testcases are from the issue.
Fixes 142
=> Add testcases for issue 142.

build/cloudbuild/build-cloudbuild.yaml
=> Increase build timeout to 1 hour.

pkg/gcv/configs/config.go
=> feat: Warn if users have v1alpha1 templates and constraints

cmd/policy-tool/debug/debug.go
Make the debug command a bit more useful by printing evaluation results.
=> Print results of debug command execution.

pkg/asset/asset.go
Update the asset validation to check for v2 org policy too.
=> Update the asset validation to check for v2 org policy too.

pkg/asset/asset.go, pkg/gcptarget/gcptarget.go, pkg/gcv/parallelvalidator_test.go, pkg/gcv/validator_test.go
The PR will:
1. Add support for v2_org_policies in HandleReview method.
2. Increase coverage of TestReviewAsset by checking violations for IAM Policy, Resource, Org Policy and V2 Org Policies.
=> Update HandleReview method and add tests to TestReviewAsset
